language: node_js
node_js: 'lts/*'
dist: trusty
sudo: required

deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now
    skip_cleanup: true
    on:
      master: true
